version: "3"
services:
  celebrity_jsp:
    container_name: celebrity_jsp
    image: hexator/celebrity
    ports:
      - 80:80
    depends_on:
      - celebrity_mysql

  celebrity_mysql:
    container_name: celebrity_mysql
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: celebrity
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

